# Generated by Django 5.2 on 2026-01-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_customer_vendor'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name snapshot at invoice time', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name snapshot at order time', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name (used when customer master is not linked)', max_length=255),
        ),
    ]
