# Generated by Django 5.2 on 2026-01-20 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rejection Reason',
                'verbose_name_plural': 'Rejection Reasons',
                'db_table': 'qc_rejection_reasons',
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('inspection_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('grn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspection', to='inventory.goodsreceiptnote')),
            ],
            options={
                'verbose_name': 'Quality Inspection',
                'verbose_name_plural': 'Quality Inspections',
                'db_table': 'quality_inspections',
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('grn_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_items', to='inventory.goodsreceiptitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qualityinspection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_items', to='items.item')),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_items', to='quality.rejectionreason')),
            ],
            options={
                'verbose_name': 'Quality Inspection Item',
                'verbose_name_plural': 'Quality Inspection Items',
                'db_table': 'quality_inspection_items',
            },
        ),
    ]
