# Generated by Django 5.2 on 2026-01-20 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='Unique item code / SKU', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Item name or description', max_length=255)),
                ('item_type', models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Good'), ('SEMI', 'Semi Finished'), ('SERVICE', 'Service'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
    ]
