# Generated by Django 6.0.1 on 2026-01-21 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(help_text='Unique item code', max_length=50, unique=True)),
                ('item_name', models.CharField(help_text='Product/Item name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('hsn_code', models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=20)),
                ('unit', models.CharField(default='PCS', help_text='Unit of measurement (PCS, KG, LTR, MTR, etc.)', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
