# Generated by Django 6.0.1 on 2026-01-21 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(editable=False, help_text='Auto-generated: EEL/YEAR/NUMBER', max_length=50, unique=True)),
                ('requisition_date', models.DateField(help_text='Date of requisition')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes')),
                ('is_assigned', models.BooleanField(default=False, help_text='Whether vendors are assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this requisition', on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'requisitions',
                'ordering': ['-requisition_number'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Required quantity', max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Item',
                'verbose_name_plural': 'Requisition Items',
                'db_table': 'requisition_items',
            },
        ),
        migrations.CreateModel(
            name='VendorRequisitionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(help_text='User who made the assignment', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(help_text='Reference requisition', on_delete=django.db.models.deletion.PROTECT, to='requisitions.requisition')),
                ('vendor', models.ForeignKey(help_text='Assigned vendor', on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Assignment',
                'verbose_name_plural': 'Vendor Assignments',
                'db_table': 'vendor_requisition_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.vendorrequisitionassignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisitions.requisitionitem')),
            ],
            options={
                'verbose_name': 'Vendor Item',
                'verbose_name_plural': 'Vendor Items',
                'db_table': 'vendor_requisition_items',
            },
        ),
    ]
