# Generated by Django 6.0.1 on 2026-01-21 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(help_text='Unique vendor code', max_length=50, unique=True)),
                ('vendor_name', models.CharField(help_text='Vendor/Supplier name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Complete address')),
                ('gst_number', models.CharField(blank=True, help_text='GST registration number', max_length=50)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['vendor_name'],
            },
        ),
    ]
